%% REFLECTION COEFFICIENT
R.QRD_TMM = calculateQRDReflection(Geo.numberWells,Geo.wellWidth,...
 Freq.designFreq,Freq.f_min,Freq.f_max,Freq.df,rho_0,c_0);
R.QRM_TMM = calculateMetadiffuserReflection(Geo.numberWells,optgeo,Freq.f_min,...
    Freq.f_max,Freq.df,stinson_constants);
R.flat_TMM = ones(size(R.QRD_TMM));

%% SCATTERED PRESSURE
R_big.QRD = discretizeDiffuserReflection(Geo.numberWells,...
                                            Geo.xpoints,R.QRD_TMM);
R_big.QRM = discretizeDiffuserReflection(Geo.numberWells,...
                                            Geo.xpoints,R.QRM_TMM);
R_big.flat = discretizeDiffuserReflection(Geo.numberWells,...
                                            Geo.xpoints,R.flat_TMM);

for ii = 1:size(R_big.QRD,1) %calculate scattered pressure
    Ps.QRD_TMM(ii,:) = fftfraunhofer(Angle.Vector,R_big.QRD(ii,:)...
        ,Freq.waveno(ii),Geo.xpoints);
    Ps.QRM_TMM(ii,:)  = fftfraunhofer(Angle.Vector,R_big.QRM(ii,:)...
        ,Freq.waveno(ii),Geo.xpoints);
    Ps.flat_TMM(ii,:)  = fftfraunhofer(Angle.Vector,R_big.flat(ii,:)...
        ,Freq.waveno(ii),Geo.xpoints);
end